name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build web-app
        run: |
          npm ci
          npm run build
      - name: Configure Artifact
        uses: actions/configure-pages@v1
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
            name: github-pages
            path: ./build
            if-no-files-found: error
      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
