name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build web-app
        run: |
          npm ci
          npm run build
      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
